### ISSUE TITLE
https cannot be connected from rumors-site docker container

### ISSUE THREAD

**Issue by MrOrz** [cofacts/rumors-deploy#2]
rumors-site 有做 server-side render
因此 API endpoint 都是使用 https://cofacts-api.g0v.tw 。

但 rumors-site 的 container 裡面似乎沒辦法連到 https://cofacts-api.g0v.tw 。

https://g0v-tw.slack.com/archives/C2PPMRQGP/p1492774409549510

**Comment by darkbtf** [comment]
ufw 把 443 打開就會動了!!!
但為什麼從外面就連得進去
